name: Scala Plugin Build

on:
  push:
    branches: [ idea201.x ]
  pull_request:
    branches: [ idea201.x ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: olafurpg/setup-scala@v5
      with:
        java-version: adopt@1.8
    - name: Install JDK 8
      run: jabba install adopt@1.8.0-242
    - name: Install JDK 11
      run: jabba install adopt@1.11.0-6
    - name: package and compile tests
      run: sbt clean packagePlugin test:compile
    - name: Cache coursier cache
      uses: actions/cache@v1
      with:
        path: ~/.coursier/cache
        key: ${{ runner.os }}-coursier-cache-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/**/*.scala') }}
    - name: Cache ivy cache
      uses: actions/cache@v1
      with:
        path: ~/.ivy2/cache
        key: ${{ runner.os }}-ivy-cache-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/**/*.scala') }}
    - name: Cache sbt
      uses: actions/cache@v1
      with:
        path: ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/**/*.scala') }}
    - name: Cache IntelliJ SDK
      uses: actions/cache@v1
      with:
        path: ~/.ScalaPluginIC
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/**/*.scala') }}
    - name: assorted tests
      run: sbt runFastTests
