name: Scala Plugin Build

on:
  push:
    branches: [ idea201.x ]
  pull_request:
    branches: [ idea201.x ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: package and compile tests
      run: sbt clean packagePlugin test:compile
    - name: assorted tests
      run: sbt runFastTests
